{
 "title": "AutoTesting Webapp",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Uso de CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{name=\"nginx\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "container_cpu_load_average_10s{name=\"django\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "container_cpu_load_average_10s{name=\"postgres\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "container_cpu_load_average_10s{name=\"celery\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "container_cpu_load_average_10s{name=\"redis\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Uso de RAM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{name=\"nginx\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "container_memory_max_usage_bytes{name=\"django\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "container_memory_max_usage_bytes{name=\"postgres\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "container_memory_max_usage_bytes{name=\"celery\"}",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "container_memory_max_usage_bytes{name=\"redis\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Tráfico de Red - Recibido",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{name=\"nginx\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{name=\"django\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{name=\"postgres\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{name=\"celery\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{name=\"redis\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Tráfico de Red - Enviado",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{name=\"nginx\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{name=\"django\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{name=\"postgres\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{name=\"celery\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{name=\"redis\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}